### ISSUE TITLE
Website updates

### ISSUE THREAD

**Issue by illusional** [openwdl/openwdl.github.io#1]
I like that we're open sourcing the website! I was going through it and noticed a few points that could be updated:

- Emphasise the specification and tutorials, as they're usually the first things people want to see.
- Add the engines that support WDL.
- Draft language specification could be updated with [v1.0](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md)
- After openwdl/wdl/issues/352 is resolved, we could update the WDL support forum link to that.
  - Link back for legacy reasons though?
- Update the following text:
> Over the coming months we will be moving the online presence for WDL from the broadinstitute.org domain to openwdl.org but for now we recommend people use the following web resources

To something like:

> The OpenWDL community has been moved from the broadinstitute.org to openwdl.org. We'd like to acknowledge the Broad Institute for passing the project onto the community, and here are resources that they provide:

**Comment by patmagee** [comment]
@illusional I made some preliminary changes addressing your 3 and final points!
