### ISSUE TITLE
Investigate Static site generation tools

### ISSUE THREAD

**Issue by patmagee** [openwdl/openwdl.github.io#3]
At the moment we use a single page html as our website, this was done simpy to fullfill our needs at the time. However as the community evolves it would be great if we could grow the website to include information such as:

- tutorials
- FAQ
- Getting started guides
- A Blog even???

IN order to facilitate this, we should investigate static ste generation tools. I am familiar with Jekyll, howver I know we can get pretty much most things working with git pages if we try.

**Comment by DavyCats** [comment]
Github pages uses jekyll in the backend. The [biowdl docs pages](https://biowdl.github.io/) are made using github pages/jekyll, eg: https://github.com/biowdl/RNA-seq/tree/gh-pages and https://github.com/biowdl/biowdl.github.io.

**Comment by vsmalladi** [comment]
Are using static pages to generate githubpages
